### ISSUE TITLE
With latest version of redux-api-middleware, CALL_API is deprecated

### ISSUE THREAD

**Issue by jeremym** [hamxabaig/redux-api-middleware-interceptor#2]
On implementation, if the dev has used RSAA for the call, none of the interceptors are executed.  Suggested solution: coding for both the depredated CALL_API and the new RSAA (see isRSAA and the following text in the readme: `The CALL_API symbol is replaced with the RSAA string as the top-level RSAA action key. CALL_API is aliased to the new value as of 2.0, but this will ultimately be deprecated.`

Quick solution = simply replacing CALL_API with RSAA in index.js

**Comment by hamxabaig** [comment]
@jeremym I see, are you talking about 2.0 version of [redux-api-middleware](https://github.com/agraboso/redux-api-middleware)? Because this package uses 2.0 of redux-api-middleware (check the dependencies)

**Comment by jeremym** [comment]
Hey hey.  My project is using 3.0.  To support 3.0, I simply changed `CALL_API` to `RSAA` in `index.js` (the quick and dirty solution).  Handling both is certainly possible.

**Comment by hamxabaig** [comment]
@jeremym Thank for reporting the issue. This should be fixed in `v1.0.4` 🎉  The `onRequestError` method is also patched to handle the case when the response is not JSON.
